<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Tools\Nexus.Tools.csproj" />
    <ProjectReference Include="..\Nexus.Security\Nexus.Security.csproj" />
    <ProjectReference Include="..\Nexus.Data\Nexus.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
