// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Data;

#nullable disable

namespace Nexus.Data.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260818102117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Data.Entities.AgentAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.ToTable("AgentActions");
                });

            modelBuilder.Entity("Nexus.Data.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OriginalPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AgentRuns");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("AgentRunId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("Nexus.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("SpentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Year", "Quarter");

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllocatedAmount = 50000.00m,
                            DepartmentId = 1,
                            Quarter = "Q3",
                            SpentAmount = 58500.00m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            AllocatedAmount = 30000.00m,
                            DepartmentId = 2,
                            Quarter = "Q3",
                            SpentAmount = 22000.00m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            AllocatedAmount = 45000.00m,
                            DepartmentId = 3,
                            Quarter = "Q3",
                            SpentAmount = 41200.00m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            AllocatedAmount = 60000.00m,
                            DepartmentId = 4,
                            Quarter = "Q3",
                            SpentAmount = 51000.00m,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Nexus.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Information Technology and Systems Software Development",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Human Resources & Talent Management",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Brand Strategy, Growth & Digital Marketing",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Business Operations, Logistics & Maintenance",
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("Nexus.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Designation = "Senior .NET Developer",
                            Email = "tariq.mahmood@nexus.local",
                            ExperienceYears = 5,
                            Name = "Tariq Mahmood",
                            Salary = 75000.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Designation = "Lead IT Architect",
                            Email = "sarah.jenkins@nexus.local",
                            ExperienceYears = 8,
                            Name = "Sarah Jenkins",
                            Salary = 95000.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Designation = "HR Specialist",
                            Email = "maria.garcia@nexus.local",
                            ExperienceYears = 4,
                            Name = "Maria Garcia",
                            Salary = 65000.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 4,
                            Designation = "Operations Lead",
                            Email = "bilal.ahmed@nexus.local",
                            ExperienceYears = 6,
                            Name = "Bilal Ahmed",
                            Salary = 70000.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Nexus.Data.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150.00m,
                            Description = "Visual Studio Pro Subscription",
                            EmployeeId = 1,
                            ExpenseDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpenseType = 4,
                            Status = 4
                        },
                        new
                        {
                            Id = 2,
                            Amount = 350.00m,
                            Description = "Team Lunch Expense (Exceeds $50 per person limit)",
                            EmployeeId = 1,
                            ExpenseDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpenseType = 2,
                            Status = 5
                        },
                        new
                        {
                            Id = 3,
                            Amount = 400.00m,
                            Description = "HR Compliance Certification Course",
                            EmployeeId = 3,
                            ExpenseDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpenseType = 5,
                            Status = 4
                        });
                });

            modelBuilder.Entity("Nexus.Data.Entities.OnboardingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SystemTarget")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("OnboardingTasks");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContentSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "HR",
                            ContentSummary = "Covers onboarding requirements, standard salary bands (Mid-Level Developer $65k-$72k), equipment requests, and welcome procedures.",
                            DocumentPath = "policies/HR_Policy.pdf",
                            IsActive = true,
                            Title = "Employee Onboarding & Compensation Policy",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "IT",
                            ContentSummary = "Rules for developer web portal ticketing, LDAP/Active Directory provisioning, and security credentials.",
                            DocumentPath = "policies/IT_Policy.pdf",
                            IsActive = true,
                            Title = "IT System Access & Provisioning Policy",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Expense",
                            ContentSummary = "Meal expenses are capped at $50 per person. Software tools require prior IT approval. Receipts mandatory above $25.",
                            DocumentPath = "policies/Expense_Policy.pdf",
                            IsActive = true,
                            Title = "Expense Reimbursement & Meal Policy",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Compensation",
                            ContentSummary = "Bulk salary increases above 5% require management approval and a formal Plan of Action impact assessment.",
                            DocumentPath = "policies/Salary_Policy.pdf",
                            IsActive = true,
                            Title = "Salary Adjustment & Compensation Band Policy",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Nexus.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@nexus.local",
                            Name = "System Admin",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hr.manager@nexus.local",
                            Name = "HR Manager",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("Nexus.Data.Entities.AgentAction", b =>
                {
                    b.HasOne("Nexus.Data.Entities.AgentRun", "AgentRun")
                        .WithMany("Actions")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRun");
                });

            modelBuilder.Entity("Nexus.Data.Entities.AgentRun", b =>
                {
                    b.HasOne("Nexus.Data.Entities.User", "User")
                        .WithMany("AgentRuns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Approval", b =>
                {
                    b.HasOne("Nexus.Data.Entities.AgentAction", "AgentAction")
                        .WithMany("Approvals")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nexus.Data.Entities.AgentRun", "AgentRun")
                        .WithMany("Approvals")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentAction");

                    b.Navigation("AgentRun");
                });

            modelBuilder.Entity("Nexus.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("Nexus.Data.Entities.AgentRun", "AgentRun")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nexus.Data.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AgentRun");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Budget", b =>
                {
                    b.HasOne("Nexus.Data.Entities.Department", "Department")
                        .WithMany("Budgets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Employee", b =>
                {
                    b.HasOne("Nexus.Data.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Expense", b =>
                {
                    b.HasOne("Nexus.Data.Entities.Employee", "Employee")
                        .WithMany("Expenses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Nexus.Data.Entities.OnboardingTask", b =>
                {
                    b.HasOne("Nexus.Data.Entities.AgentRun", "AgentRun")
                        .WithMany("OnboardingTasks")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nexus.Data.Entities.Employee", "Employee")
                        .WithMany("OnboardingTasks")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRun");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Nexus.Data.Entities.AgentAction", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("Nexus.Data.Entities.AgentRun", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Approvals");

                    b.Navigation("AuditLogs");

                    b.Navigation("OnboardingTasks");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Department", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Nexus.Data.Entities.Employee", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("OnboardingTasks");
                });

            modelBuilder.Entity("Nexus.Data.Entities.User", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
